config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  root "posts#index"
  get '/about', to: 'pages#about'
  get 'feed', to: 'feeds#rss', format: 'rss'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 5}
  validates :body, presence: true
  acts_as_taggable #to make the post tagable
  mount_uploader :picture, PictureUploader #hook the uploader to the post
  belongs_to :user
  validate  :picture_size

  private
    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :get_post, only: [:create, :destroy]

  def create
    @comment = @post.comments.create(comment_params)

    redirect_to post_path(@post)
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end

  private
    # => get the current post
    def get_post
      @post = Post.find(params[:post_id])
    end

    # => get the comments params through strong params.
    def comment_params
      params.require(:comment).permit(:name, :body)
    end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  layout false
  def rss
    @posts = Post.all.order("created_at DESC")
  end
end

app/controllers/pages_controller.rb
#Static Page Controller
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :get_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    #This if statement is used to handle filtering by Tags, Useremail(Author),
    #or Tilte
    if params[:tag] #this one is for tag filtering
      @posts = Post.tagged_with(params[:tag]).order("created_at DESC")
    elsif params[:search] #this one is for title search keywords
      @posts = Post.where("title LIKE :t", {t: "%#{params[:search].upcase}%"})
    elsif params[:user_email] #this one is for finding user email related to the
                              # post to retrieve all his posts
      user_id = User.find_by(email: params[:user_email]).id
      @posts = Post.where(user_id: user_id)
    else
      @posts = Post.all.order("created_at DESC")
    end
  end

  def new
    @post = Post.new
  end

  def show
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.title = @post.title.upcase
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    user_id = current_user.id
    if (current_user.id == @post.user_id)
      @post.destroy
      redirect_to root_path
    else
      flash[:alert] = "Your are not the Post Owner, You can't Delete it"
      render 'show'
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :tag_list, :picture)
    end

    def get_post
      @post = Post.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def get_post_tags(post)
    raw post.tag_list.map{ |t| link_to t, {controller: "posts", action: "index",
                                           tag: t} }.join(', ')
  end

  def get_post_author(post)
    link_to User.find(post.user_id).email,
                      {controller: "posts", action: "index",
                       user_email: User.find(post.user_id).email}
  end
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <div class="comment_name">
      <strong><%= comment.name %></strong>
      (<%= time_ago_in_words(comment.created_at) %> ago.)
    </div>
    <div class="comment_body">
      <%= simple_format comment.body %>
    </div>
  </div>
  
  <% if user_signed_in? %>
      <%= link_to "Delete", [@post, comment],
                  method: :delete,
                  class: "button",
                  data: {confirm: "Are you sure?"} %>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
    <br>
    <%= f.label :body %><br>
    <%= f.text_area :body, size: "25x5" %>
    <br>
    <%= f.submit "Comment" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link type="application/rss+xml" rel="alternate" href="<%= feed_url %>" title="Simple Blog RSS feed">
  <%= csrf_meta_tags %>
</head>

<body>
  <!-- Page Sidebar -->
  <div id="sidebar">
    <div id="logo">
      <%= link_to root_path do %>
        <%= image_tag "logo.svg", width: "40px" %>
      <% end %>
    </div>
    <ul>
      <% if user_signed_in? %>
      <li>Welcome, <%= current_user.email.split('@')[0] %></li>
      <% end %>
      <li class="category">Website</li>
      <li><%= link_to "Blog", root_path %></li>
      <li><%= link_to "About", about_path %></li>
    </ul>
    <ul>
      <li class="category">Social</li>
      <li> <a href="https://eg.linkedin.com/in/heshamsalahuldeen">Hesham Salah</a> </li>
    </ul>
  </div>

  <div id="main_content">
    <div id="header">
      <!-- Check if you are in the home page -->
      <% if current_page?(root_path) %>
        All Posts
      <% elsif current_page?(about_path) %>
        <p>About</p>
      <% else %>
        <%= link_to "Back to home page", root_path %>
      <% end %>

      <% if user_signed_in? %>
          <button class="buttons button">
            <%= link_to "New Post", new_post_path %>
          </button>
          <button class="buttons button">
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          </button>
      <% else %>
          <button class="buttons button">
            <%= link_to "Signin", new_user_session_path %>
          </button>
          <button class="buttons button">
            <%= link_to "Signup", new_user_registration_path %>
          </button>
      <% end %>
    </div>

    <% if current_page?(root_path) %>
      <div class="searchbox">
        <!-- A search box for filtering by title -->
        <%= form_tag(posts_path, method: 'get')  do %>
          <%= text_field_tag :search, nil, placeholder: "Enter Post Title..."%>
          <%= submit_tag "Search", name: nil, class: "button" %>
        <% end %>
      </div>
    <% end %>

    <!-- Error Messages Display -->
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "#{name}") %>
    <% end %>

    <!-- Main Content -->
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
  <div id="content">
    Gluten-free lomo trust fund cronut. Cronut vegan asymmetrical,
    listicle semiotics wolf pug thundercats gluten-free poutine sustainable everyday carry.
    Hammock bushwick photo booth, VHS mumblecore forage heirloom semiotics aesthetic kogi fanny pack.
    Marfa dreamcatcher salvia echo park. Farm-to-table four loko biodiesel locavore blog poutine, godard bitters XOXO banjo.
    Poutine chartreuse food truck stumptown, typewriter chillwave bicycle rights seitan pinterest.
    Synth single-origin coffee kombucha, pabst VHS food truck blog marfa pork belly hella stumptown flexitarian DIY
    thundercats jean shorts.
  </div>
</div>

app/views/posts/_errors.html.erb
<!-- Render the errors for the new and edit forms -->

<% if @post.errors.any? %>
  <div id="errors">
    <h2> <%= pluralize(@post.errors.count, "error") %> Prevented saving.</h2>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/posts/_form.html.erb
<!-- html: { multipart: true } => this line is for the carrierwave gem for picture upload -->
<%= form_for(@post, html: { multipart: true }) do |f| %>

  <div class="filed">
    <%= f.label :title %> <br>
    <%= f.text_field :title %>
  </div>

  <div class="filed">
    <%= f.label :body %> <br>
    <%= f.text_area :body %>
  </div>

  <div class="filed">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div>

  <div class="field">
    <!-- this span holds the picture upload button -->
    <span class="picture">
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    </span>
    <%= f.submit %>
  </div>

<% end %>

<!-- a JQUERY script to issue an alert if a user tries to upload an image that’s too big -->
<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Edit Post</h1>
  <%= render 'errors' %>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title">
      <%= link_to post.title, post %>
    </h2>

    <p class="date_and_author">
      <%= post.created_at.strftime("%B %d %Y") %>
      <!--
        get_post_author(post) is a PostsHelper method that
        retrieve the user_email that created this post
        @parameters => post
      -->
      | Created By: <%= get_post_author(post) %>
    </p>

    <p class="body">
      <%= simple_format post.body %>
      <%= image_tag post.picture.url if post.picture? %>
      <hr>
      <!-- get_post_tags(post) is a PostsHelper method that retrieve a tag list and put them into links -->
      Tags: <strong style="color: blue;"><%= get_post_tags(post) %></strong>
    </p>
  </div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1>New Post</h1>
  <%= render 'errors' %>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title">
    <%= @post.title %>
  </h1>

  <p class="date">
    Created At: <%= time_ago_in_words(@post.created_at) %> ago.
    <% if user_signed_in? && current_user.id == @post.user_id %>
      | <strong style="color: green;">
        <%= link_to "Edit", edit_post_path(@post) %>
        </strong>
      | <strong style="color: red;">
        <%= link_to "Delete", post_path(@post), method: :delete,
            data: {confirm: "Are you sure?"}%>
        </strong>
    <% end %>
  </p>

  <p class="body">
    <%= simple_format @post.body %>
    <%= image_tag @post.picture.url if @post.picture? %>
  </p>

  <hr>
  <p>
    Tags: <strong style="color: blue;"><%= get_post_tags(@post) %></strong>
  </p>
  <div id="comments">
    <h2><%= @post.comments.count %> comments</h2>
    <%= render @post.comments %>
    <% if user_signed_in? %>
      <h3>Add a comment</h3>
      <%= render "comments/form" %>
    <% end %>
  </div>
</div>